<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-04T17:14:00 IST" name="Surefire suite" finished-at="2025-03-04T17:14:05 IST" duration-ms="5370">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.TestNgtestRunner@d5b810e]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2025-03-04T17:14:00 IST" name="Surefire test" finished-at="2025-03-04T17:14:05 IST" duration-ms="5370">
      <class name="Runner.TestNgtestRunner">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:Runner.TestNgtestRunner@d5b810e]" started-at="2025-03-04T17:14:00 IST" name="setUpClass" finished-at="2025-03-04T17:14:00 IST" duration-ms="659" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2f04993d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:Runner.TestNgtestRunner@d5b810e]" started-at="2025-03-04T17:14:00 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2025-03-04T17:14:05 IST" duration-ms="4613" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["Verify if place is successfully added into the AddPlaceAPI"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Validate Add Place Api's"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at StepDefinitions.stepdefAddplace.validate_api_call_is_success_status_code_is(stepdefAddplace.java:69)
at âœ½.validate Api call is success status code is 200(file:///C:/Users/VPAVAN/ec1/Bdd2/src/test/java/feature/placevalidations.feature:18)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:Runner.TestNgtestRunner@d5b810e]" started-at="2025-03-04T17:14:05 IST" name="tearDownClass" finished-at="2025-03-04T17:14:05 IST" duration-ms="46" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- Runner.TestNgtestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
